FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
        curl \
        nginx \
        python3 \
        python3-dev \
	python3-setuptools \
        python3-pip && \
        pip3 install -U pip setuptools  && \
   rm -rf /var/lib/apt/lists/* && \
   apt-get auto-remove
